CREATE DATABASE VENTA
GO

USE VENTA
GO

CREATE SCHEMA PERSONA
GO

CREATE SCHEMA VENTA
GO

CREATE TABLE PERSONA.UBIGEO(
	CODUBI CHAR(6),
	DISTUBI VARCHAR(30),
	PROUBI VARCHAR(30),
	DEPUBI VARCHAR(30),
	CONSTRAINT PK_CODUBI PRIMARY KEY(CODUBI)
)
GO

CREATE TABLE PERSONA.PERSONA(
	IDPER INT IDENTITY(1,1),
	NOMPER VARCHAR(30),
	APEPER VARCHAR(40),
	DNIPER CHAR(8),
	CELPER CHAR(9),
	DIRPER VARCHAR(70),
	CODUBI CHAR(6),
	TIPPER CHAR(1),
	IDSUC INT,
	USUPER VARCHAR(10),
	PASPER VARCHAR(50),
	ESTPER CHAR(1) DEFAULT 'A',
	CONSTRAINT PK_IDPER PRIMARY KEY(IDPER)
)
GO

CREATE TABLE PERSONA.SUCURSAL(
	IDSUC INT IDENTITY(1,1),
	NOMSUC VARCHAR(30),
	DESCSUC VARCHAR(70),
	DIRSUC VARCHAR(100),
	CODUBI CHAR(6),
	ESTSUC CHAR(1),
	CONSTRAINT PK_IDSUC PRIMARY KEY(IDSUC)
)
GO

CREATE TABLE VENTA.EQUIPO(
	IDEQU INT IDENTITY(1,1),
	NOMEQUI VARCHAR(30),
	DESCEQU VARCHAR(50),
	CATEQUI CHAR(2),
	PREEQUI DECIMAL(8,2),	
	ESTEQU CHAR(1) DEFAULT 'A',
	CONSTRAINT PK_IDEQU PRIMARY KEY(IDEQU)
)
GO

CREATE TABLE VENTA.VENTA(
	IDVEN INT IDENTITY(1,1),
	IDPER INT,
	FECVEN DATE,
	ESTVEN CHAR(1),
	CONSTRAINT PK_IDVEN PRIMARY KEY(IDVEN)
)
GO

CREATE TABLE VENTA.VENTA_DETALLE(
	IDVENDET INT IDENTITY(1,1),
	IDVEN INT,
	IDEQU INT,
	CANT INT,
	CONSTRAINT PK_IDVENDET PRIMARY KEY(IDVENDET)
)
GO

ALTER TABLE PERSONA.PERSONA
	ADD CONSTRAINT FK_UBIGEO FOREIGN KEY(CODUBI)
	REFERENCES PERSONA.UBIGEO(CODUBI)

ALTER TABLE PERSONA.PERSONA
	ADD CONSTRAINT FK_SUCURSAL FOREIGN KEY(IDSUC)
	REFERENCES PERSONA.SUCURSAL(IDSUC)

ALTER TABLE PERSONA.SUCURSAL
	ADD CONSTRAINT FK_UBIGEO1 FOREIGN KEY(CODUBI)
	REFERENCES PERSONA.UBIGEO(CODUBI)

ALTER TABLE VENTA.VENTA
	ADD CONSTRAINT FK_PERSONA FOREIGN KEY(IDPER)
	REFERENCES PERSONA.PERSONA(IDPER)

ALTER TABLE VENTA.VENTA_DETALLE
	ADD CONSTRAINT FK_VENTA FOREIGN KEY(IDVEN)
	REFERENCES VENTA.VENTA(IDVEN)

ALTER TABLE VENTA.VENTA_DETALLE
	ADD CONSTRAINT FK_EQUIPO FOREIGN KEY(IDEQU)
	REFERENCES VENTA.EQUIPO(IDEQU)