SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[vw_Boleta]
AS
	SELECT 
		VT.IDVEN,
		CONCAT(PE.NOMPER, ' ', PE.APEPER) AS PERSONA,
		PE.DNIPER,
		PE.DIRPER,
		EQ.NOMEQUI,
		VD.CANT,
		(PR.PREVEN * VD.CANT) AS SUBT
	FROM VENTA.VENTA AS VT
		INNER JOIN PERSONA.PERSONA AS PE
			ON PE.IDPER = VT.IDPER			
		LEFT JOIN Venta.VENTA_DETALLE AS VD
			ON VD.IDVEN = VT.IDVEN
		LEFT JOIN VENTA.EQUIPO AS EQ
			ON EQ.IDEQU = VD.IDEQU
		LEFT JOIN VENTA.PRECIO AS PR
			ON PR.IDEQU = EQ.IDEQU
	WHERE PR.ESTPRE = 'A'									
GO
