CREATE OR REPLACE FORCE VIEW team01.vw_ordcocina (coddetven,tippla,pedido,obsvendet,cant) AS
SELECT VD.CODDETVEN ,
          PLATO.TIPPLA ,
          CONCAT(ASIGNACION.CODMEN, PLATO.NOMPLA) PEDIDO  ,
          VD.OBSVENDET ,
          VD.CANT 
     FROM venta_team01.VENTA_DETALLE VD
            LEFT JOIN venta_team01.ASIGNACION    ON ASIGNACION.CODASIG = VD.CODASIGMEN
            LEFT JOIN venta_team01.VENTA    ON VENTA.CODVEN = VD.CODVEN
            LEFT JOIN venta_team01.PLATO    ON PLATO.CODPLA = VD.CODPLA
    WHERE  UTILS.CONVERT_TO_VARCHAR2(VENTA.FECVEN,11) = UTILS.CONVERT_TO_VARCHAR2(SYSDATE,11)
             AND vd.CODVEN LIKE 'B%'
             AND ESTDETVENT = 'A';