CREATE TABLE [PERSONA].[UBIGEO]
(
[CODUBI] [char] (6) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DISTUBI] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[PROUBI] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[DEPUBI] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[UBIGEO] ADD CONSTRAINT [PK_CODUBI] PRIMARY KEY CLUSTERED  ([CODUBI]) ON [PRIMARY]
GO
