CREATE TABLE [PERSONA].[SUCURSAL]
(
[IDSUC] [int] NOT NULL IDENTITY(1, 1),
[NOMSUC] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[DESCSUC] [varchar] (70) COLLATE Modern_Spanish_CI_AS NULL,
[DIRSUC] [varchar] (100) COLLATE Modern_Spanish_CI_AS NULL,
[CODUBI] [char] (6) COLLATE Modern_Spanish_CI_AS NULL,
[ESTSUC] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[SUCURSAL] ADD CONSTRAINT [PK_IDSUC] PRIMARY KEY CLUSTERED  ([IDSUC]) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[SUCURSAL] ADD CONSTRAINT [FK_UBIGEO1] FOREIGN KEY ([CODUBI]) REFERENCES [PERSONA].[UBIGEO] ([CODUBI])
GO
