CREATE TABLE [PERSONA].[PERSONA]
(
[IDPER] [int] NOT NULL IDENTITY(1, 1),
[NOMPER] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[APEPER] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[DNIPER] [char] (8) COLLATE Modern_Spanish_CI_AS NULL,
[CELPER] [char] (9) COLLATE Modern_Spanish_CI_AS NULL,
[DIRPER] [varchar] (70) COLLATE Modern_Spanish_CI_AS NULL,
[CODUBI] [char] (6) COLLATE Modern_Spanish_CI_AS NULL,
[TIPPER] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[IDSUC] [int] NULL,
[USUPER] [varchar] (10) COLLATE Modern_Spanish_CI_AS NULL,
[PASPER] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[ESTPER] [char] (1) COLLATE Modern_Spanish_CI_AS NULL CONSTRAINT [DF__PERSONA__ESTPER__398D8EEE] DEFAULT ('A')
) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[PERSONA] ADD CONSTRAINT [PK_IDPER] PRIMARY KEY CLUSTERED  ([IDPER]) ON [PRIMARY]
GO
ALTER TABLE [PERSONA].[PERSONA] ADD CONSTRAINT [FK_SUCURSAL] FOREIGN KEY ([IDSUC]) REFERENCES [PERSONA].[SUCURSAL] ([IDSUC])
GO
ALTER TABLE [PERSONA].[PERSONA] ADD CONSTRAINT [FK_UBIGEO] FOREIGN KEY ([CODUBI]) REFERENCES [PERSONA].[UBIGEO] ([CODUBI])
GO
