CREATE TABLE [VENTA].[VENTA]
(
[IDVEN] [int] NOT NULL,
[IDPER] [int] NULL,
[IDVED] [int] NULL,
[FECVEN] [date] NULL,
[ESTVEN] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[VENTA] ADD CONSTRAINT [PK_IDVEN] PRIMARY KEY CLUSTERED  ([IDVEN]) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[VENTA] ADD CONSTRAINT [FK_PERSONA] FOREIGN KEY ([IDPER]) REFERENCES [PERSONA].[PERSONA] ([IDPER])
GO
ALTER TABLE [VENTA].[VENTA] ADD CONSTRAINT [FK_VENDEDOR] FOREIGN KEY ([IDVED]) REFERENCES [PERSONA].[PERSONA] ([IDPER])
GO
