CREATE TABLE [VENTA].[EQUIPO]
(
[IDEQU] [int] NOT NULL IDENTITY(1, 1),
[NOMEQUI] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[DESCEQU] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL,
[CATEQUI] [char] (2) COLLATE Modern_Spanish_CI_AS NULL,
[CANTEQU] [int] NULL,
[ESTEQU] [char] (1) COLLATE Modern_Spanish_CI_AS NULL CONSTRAINT [DF__EQUIPO__ESTEQU__3E52440B] DEFAULT ('A'),
[IMGEQU] [varchar] (500) COLLATE Modern_Spanish_CI_AS NULL,
[MAREQU] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[EQUIPO] ADD CONSTRAINT [PK_IDEQU] PRIMARY KEY CLUSTERED  ([IDEQU]) ON [PRIMARY]
GO
