CREATE TABLE [VENTA].[PRECIO]
(
[IDPRE] [int] NOT NULL IDENTITY(1, 1),
[IDEQU] [int] NULL,
[PRECOM] [decimal] (8, 2) NULL,
[PREVEN] [decimal] (8, 2) NULL,
[ESTPRE] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[PRECIO] ADD CONSTRAINT [PK_PRECIO] PRIMARY KEY CLUSTERED  ([IDPRE]) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[PRECIO] ADD CONSTRAINT [FK_PRECIO] FOREIGN KEY ([IDEQU]) REFERENCES [VENTA].[EQUIPO] ([IDEQU])
GO
