CREATE TABLE [VENTA].[VENTA_DETALLE]
(
[IDVENDET] [int] NOT NULL IDENTITY(1, 1),
[IDVEN] [int] NULL,
[IDEQU] [int] NULL,
[CANT] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [VENTA].[tr_VENTA]
ON [VENTA].[VENTA_DETALLE] FOR INSERT, UPDATE
AS
	UPDATE VENTA.EQUIPO
	SET EQUIPO.CANTEQU = EQ.CANTEQU - VENTA_DETALLE.CANT
	FROM VENTA.EQUIPO AS EQ,
		(SELECT IDEQU, CANT FROM  VENTA_DETALLE
			WHERE 
		IDEQU = IDEQU AND IDVENDET = (SELECT MAX(IDVENDET) from VENTA.VENTA_DETALLE)) VENTA_DETALLE
	WHERE EQ.IDEQU = VENTA_DETALLE.IDEQU
GO
ALTER TABLE [VENTA].[VENTA_DETALLE] ADD CONSTRAINT [PK_IDVENDET] PRIMARY KEY CLUSTERED  ([IDVENDET]) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[VENTA_DETALLE] ADD CONSTRAINT [FK_EQUIPO] FOREIGN KEY ([IDEQU]) REFERENCES [VENTA].[EQUIPO] ([IDEQU])
GO
ALTER TABLE [VENTA].[VENTA_DETALLE] ADD CONSTRAINT [FK_VENTA] FOREIGN KEY ([IDVEN]) REFERENCES [VENTA].[VENTA] ([IDVEN])
GO
