CREATE TABLE [VENTA].[VENTA_DETALLE]
(
[IDVENDET] [int] NOT NULL IDENTITY(1, 1),
[IDVEN] [int] NULL,
[IDEQU] [int] NULL,
[CANT] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[VENTA_DETALLE] ADD CONSTRAINT [PK_IDVENDET] PRIMARY KEY CLUSTERED  ([IDVENDET]) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[VENTA_DETALLE] ADD CONSTRAINT [FK_EQUIPO] FOREIGN KEY ([IDEQU]) REFERENCES [VENTA].[EQUIPO] ([IDEQU])
GO
ALTER TABLE [VENTA].[VENTA_DETALLE] ADD CONSTRAINT [FK_VENTA] FOREIGN KEY ([IDVEN]) REFERENCES [VENTA].[VENTA] ([IDVEN])
GO
