CREATE TABLE [VENTA].[MOVIMIENTO]
(
[IDMOV] [int] NOT NULL IDENTITY(1, 1),
[IDPER] [int] NULL,
[IDEQU] [int] NULL,
[FECMOV] [date] NULL,
[CANTMOV] [int] NULL,
[TIPMOV] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[ESTMOV] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [VENTA].[tr_INGRESO]
ON [VENTA].[MOVIMIENTO] FOR INSERT, UPDATE
AS
	UPDATE VENTA.EQUIPO
	SET EQUIPO.CANTEQU = EQ.CANTEQU + MOV.CANTMOV
	FROM VENTA.EQUIPO AS EQ,
		(SELECT IDEQU, CANTMOV, TIPMOV FROM Venta.MOVIMIENTO 
			WHERE 
		IDEQU = IDEQU AND IDMOV = (SELECT MAX(IDMOV) from Venta.MOVIMIENTO) AND TIPMOV = 'I') MOV
	WHERE EQ.IDEQU = MOV.IDEQU AND TIPMOV = 'I'
GO
ALTER TABLE [VENTA].[MOVIMIENTO] ADD CONSTRAINT [PK_MOVIMIENTO] PRIMARY KEY CLUSTERED  ([IDMOV]) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[MOVIMIENTO] ADD CONSTRAINT [FK_MOVIMIENT] FOREIGN KEY ([IDPER]) REFERENCES [PERSONA].[PERSONA] ([IDPER])
GO
ALTER TABLE [VENTA].[MOVIMIENTO] ADD CONSTRAINT [FK_MOVIMIENTO] FOREIGN KEY ([IDEQU]) REFERENCES [VENTA].[EQUIPO] ([IDEQU])
GO
