CREATE TABLE [VENTA].[MOVIMIENTO]
(
[IDMOV] [int] NOT NULL IDENTITY(1, 1),
[IDPER] [int] NULL,
[IDEQU] [int] NULL,
[FECMOV] [date] NULL,
[CANTMOV] [int] NULL,
[TIPMOV] [char] (1) COLLATE Modern_Spanish_CI_AS NULL,
[ESTMOV] [char] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[MOVIMIENTO] ADD CONSTRAINT [PK_MOVIMIENTO] PRIMARY KEY CLUSTERED  ([IDMOV]) ON [PRIMARY]
GO
ALTER TABLE [VENTA].[MOVIMIENTO] ADD CONSTRAINT [FK_MOVIMIENT] FOREIGN KEY ([IDPER]) REFERENCES [PERSONA].[PERSONA] ([IDPER])
GO
ALTER TABLE [VENTA].[MOVIMIENTO] ADD CONSTRAINT [FK_MOVIMIENTO] FOREIGN KEY ([IDEQU]) REFERENCES [VENTA].[EQUIPO] ([IDEQU])
GO
